// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxProcessor.Api.Data;

#nullable disable

namespace TaxProcessor.Api.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    [Migration("20260326052613_AddLoginEmailOtp")]
    partial class AddLoginEmailOtp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxProcessor.Api.Data.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginOtpChallengeTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LoginOtpCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginOtpCodeHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("TaxProcessor.Api.Data.TaxProgressEntity", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStepId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ProfileId", "Year", "Name");

                    b.ToTable("TaxProgress");
                });

            modelBuilder.Entity("TaxProcessor.Api.Data.TaxResponseEntity", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("FormCode")
                        .HasColumnType("text");

                    b.Property<string>("Subsection")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ProfileId", "Year", "Name", "Form", "Label", "Line");

                    b.ToTable("TaxResponse");
                });

            modelBuilder.Entity("TaxProcessor.Api.Data.TaxProgressEntity", b =>
                {
                    b.HasOne("TaxProcessor.Api.Data.ProfileEntity", "Profile")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TaxProcessor.Api.Data.TaxResponseEntity", b =>
                {
                    b.HasOne("TaxProcessor.Api.Data.TaxProgressEntity", "TaxProgress")
                        .WithMany("Responses")
                        .HasForeignKey("ProfileId", "Year", "Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxProgress");
                });

            modelBuilder.Entity("TaxProcessor.Api.Data.ProfileEntity", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("TaxProcessor.Api.Data.TaxProgressEntity", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
