using TaxProcessor.Api.Controllers;

namespace TaxProcessor.Api.Data;

// Auto-generated by AI, and may be useful, but not currently used
public partial class TaxTableFetcher
{
    // 2025 Tax Rate Schedules (IRS Rev. Proc. 2024-40).
    // Each bracket is (income threshold, marginal rate, base tax owed at that threshold).
    // Used for income above the IRS Tax Table ceiling (~$100,000) or when the HTML parse fails.
    private static readonly (int Threshold, decimal Rate, decimal BaseTax)[] SingleBrackets =
    [
        (0, 0.10m, 0m),
        (11_925, 0.12m, 1_192.50m),
        (48_475, 0.22m, 5_578.50m),
        (103_350, 0.24m, 17_651.00m),
        (197_300, 0.32m, 40_199.00m),
        (250_525, 0.35m, 57_231.00m),
        (626_350, 0.37m, 188_769.75m),
    ];

    private static readonly (int Threshold, decimal Rate, decimal BaseTax)[] MarriedJointlyBrackets =
    [
        (0, 0.10m, 0m),
        (23_850, 0.12m, 2_385.00m),
        (96_950, 0.22m, 11_157.00m),
        (206_700, 0.24m, 35_302.00m),
        (394_600, 0.32m, 80_398.00m),
        (501_050, 0.35m, 114_462.00m),
        (751_600, 0.37m, 202_154.50m),
    ];

    private static readonly (int Threshold, decimal Rate, decimal BaseTax)[] MarriedSeparatelyBrackets =
    [
        (0, 0.10m, 0m),
        (11_925, 0.12m, 1_192.50m),
        (48_475, 0.22m, 5_578.50m),
        (103_350, 0.24m, 17_651.00m),
        (197_300, 0.32m, 40_199.00m),
        (250_525, 0.35m, 57_231.00m),
        (375_800, 0.37m, 101_077.50m),
    ];

    private static readonly (int Threshold, decimal Rate, decimal BaseTax)[] HeadOfHouseholdBrackets =
    [
        (0, 0.10m, 0m),
        (17_000, 0.12m, 1_700.00m),
        (64_850, 0.22m, 7_442.00m),
        (103_350, 0.24m, 15_912.00m),
        (197_300, 0.32m, 38_460.00m),
        (250_500, 0.35m, 55_484.00m),
        (626_350, 0.37m, 187_031.50m),
    ];

    public static int CalculateTaxViaRateSchedule(FilingStatus filingStatus, int taxableIncome)
    {
        if (taxableIncome <= 0)
        {
            return 0;
        }

        var brackets = filingStatus switch
        {
            FilingStatus.Single => SingleBrackets,
            FilingStatus.MarriedFilingJointly => MarriedJointlyBrackets,
            FilingStatus.QualifyingWidow => MarriedJointlyBrackets,
            FilingStatus.MarriedFilingSeparately => MarriedSeparatelyBrackets,
            FilingStatus.HeadOfHousehold => HeadOfHouseholdBrackets,
            _ => throw new Exception($"Unsupported filing status: {filingStatus}"),
        };

        for (var i = brackets.Length - 1; i >= 0; i--)
        {
            var (threshold, rate, baseTax) = brackets[i];
            if (taxableIncome >= threshold)
            {
                return (int)Math.Round(
                    baseTax + (taxableIncome - threshold) * rate,
                    MidpointRounding.AwayFromZero
                );
            }
        }

        return 0;
    }
}
